#!/bin/bash
#
# Test MSwitch Direct demuxer CLI control
#

echo "==========================================="
echo "MSwitch Direct Demuxer - CLI CONTROL TEST"
echo "==========================================="
echo ""
echo "This test demonstrates interactive CLI switching with the mswitchdirect demuxer."
echo ""
echo "=== Setup Instructions ==="
echo "1. Start 3 UDP sources in separate terminals:"
echo ""
echo "Terminal 1 (RED):"
echo "./ffmpeg -f lavfi -re -i color=red:size=1280x720:rate=30 -vf drawtext=fontfile=/System/Library/Fonts/Supplemental/Arial.ttf:text='RED\\ %{localtime}.%{eif\\:1M*t-1K*trunc(t*1K)\\:d}':x=40:y=60:fontsize=64:fontcolor=white:box=1:boxcolor=0x00000088 -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -g 60 -f mpegts udp://127.0.0.1:12350"
echo ""
echo "Terminal 2 (GREEN):"
echo "./ffmpeg -f lavfi -re -i color=green:size=1280x720:rate=30 -vf drawtext=fontfile=/System/Library/Fonts/Supplemental/Arial.ttf:text='GREEN\\ %{localtime}.%{eif\\:1M*t-1K*trunc(t*1K)\\:d}':x=40:y=60:fontsize=64:fontcolor=white:box=1:boxcolor=0x00000088 -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -g 60 -f mpegts udp://127.0.0.1:12351"
echo ""
echo "Terminal 3 (BLUE):"
echo "./ffmpeg -f lavfi -re -i color=blue:size=1280x720:rate=30 -vf drawtext=fontfile=/System/Library/Fonts/Supplemental/Arial.ttf:text='BLUE\\ %{localtime}.%{eif\\:1M*t-1K*trunc(t*1K)\\:d}':x=40:y=60:fontsize=64:fontcolor=white:box=1:boxcolor=0x00000088 -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -g 60 -f mpegts udp://127.0.0.1:12352"
echo ""
echo "2. In a 4th terminal, run FFmpeg with mswitchdirect:"
echo ""
echo "./ffmpeg -v info -f mswitchdirect -msw_sources \"udp://127.0.0.1:12350,udp://127.0.0.1:12351,udp://127.0.0.1:12352\" -msw_port 8099 -i dummy -c:v libx264 -r 30 -preset ultrafast -g 60 -keyint_min 1 -sc_threshold 0 -pix_fmt yuv420p -f mpegts \"udp://127.0.0.1:12360?pkt_size=1316\""
echo ""
echo "3. In a 5th terminal, play the output:"
echo ""
echo "ffplay udp://127.0.0.1:12360"
echo ""
echo "=== CLI Controls ==="
echo "While FFmpeg is running, press these keys:"
echo "  0 - Switch to RED source"
echo "  1 - Switch to GREEN source"
echo "  2 - Switch to BLUE source"
echo "  m - Show status (active source and buffer info)"
echo "  ? - Show help"
echo "  q - Quit"
echo ""
echo "=== Example Session ==="
echo "1. Start with source 0 (RED)"
echo "2. Press '1' to switch to GREEN"
echo "3. Press '2' to switch to BLUE"
echo "4. Press 'm' to see status"
echo "5. Press '0' to switch back to RED"
echo ""
echo "You should see instant switching with no frozen frames!"
echo ""
echo "==========================================="

